### PR TITLE
CI setup for Testing

### PR DESCRIPTION
**Pull request by bhanuvrat**
configured for automated testing on travis-ci and deployment on heroku.
if all goes well, travis will deploy the app on heroku as soon as this PR is merged into master.

### CODE REVIEW

**Comment by theskumar** [comment]
Let's squash this to a single logical commit with a proper commit message[1]

Also, w.r.t. dotenv if would nicer to have absolute path. Something like

``` python
import dotenv
# Read key, value from .env file and load them into environment variable
# Useful to override your local or production settings, that should
# not be in version control.
dotenv.load(str(ROOT_DIR.path('.env'))
```

[1] https://github.com/agis-/git-style-guide

**Comment by bhanuvrat** [comment]
@theskumar `ROOT_DIR` is present in settings ... what about `manage.py`?

**Comment by theskumar** [comment]
@bhanuvrat you'll require to define ROOT_DIR as it's defined in settings.py or

```
import dotenv
import environ
ROOT_DIR = environ.Path(__file__) - 1
dotenv.load(str(ROOT_DIR.path('.env')))
```

**Comment by bhanuvrat** [comment]
@theskumar rebased.
looks good?

**Comment by theskumar** [comment]
@bhanuvrat yep looks perfect! :+1:

**Pull request merged**
